language: go

go:
 - 1.5
 - 1.6
 - 1.7
 - 1.8
 - tip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pdftk

install:
 - go get -u github.com/golang/lint/golint
 - go get github.com/stretchr/testify
 - go get github.com/satori/go.uuid

script:
 - golint
 - go test -cover
